version: 2.1

orbs:
  python: circleci/python@1.3.4
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: 
          name: "install behave"
          command: pip install behave
      - run:
          name: "Build and run feature file"
          command: behave mydashboadr.feature
workflows:
  main:
    jobs:
      - build